import { PersistenceSettings } from '../interfaces/persistence-settings.interface';

export const persistenceObjectStore: [string, [string, boolean][]][] = [
  ['Location', [['name', false], ['__pkey__', true]]],
  [
    'SchoolClass',
    [
      ['location.name', false],
      ['location.__pkey__', false],
      ['location.__store__', false],
      ['location', false],
      ['name', false],
      ['validityRange.start', false],
      ['validityRange.end', false],
      ['validityRange', false],
      ['__pkey__', true],
    ],
  ],
  [
    'PupilEnrollment',
    [
      ['schoolClass.location.name', false],
      ['schoolClass.location.__pkey__', false],
      ['schoolClass.location.__store__', false],
      ['schoolClass.location', false],
      ['schoolClass.name', false],
      ['schoolClass.validityRange.start', false],
      ['schoolClass.validityRange.end', false],
      ['schoolClass.validityRange', false],
      ['schoolClass.__pkey__', false],
      ['schoolClass.__store__', false],
      ['schoolClass', false],
      ['validityRange.start', false],
      ['validityRange.end', false],
      ['validityRange', false],
      ['__pkey__', true],
    ],
  ],
  ['LevelYear', [['schoolLevel', false], ['year', false], ['__pkey__', true]]],
  [
    'PupilLevelYearStatus',
    [
      ['levelYear.schoolLevel', false],
      ['levelYear.year', false],
      ['levelYear.__pkey__', false],
      ['levelYear.__store__', false],
      ['levelYear', false],
      ['validityRange.start', false],
      ['validityRange.end', false],
      ['validityRange', false],
      ['__pkey__', true],
    ],
  ],
  ['Pupil', [['__pkey__', true]]],
  ['EmailAddress', [['priorityType', false], ['value', false], ['__pkey__', true]]],
  ['PhoneNumber', [['priorityType', false], ['value', false], ['__pkey__', true]]],
  [
    'Person',
    [
      ['fullName', false],
      ['pupil.__pkey__', false],
      ['pupil.__store__', false],
      ['pupil', false],
      ['firstName', false],
      ['lastNamePrefix', false],
      ['lastName', false],
      ['primaryEmailAddress.priorityType', false],
      ['primaryEmailAddress.value', false],
      ['primaryEmailAddress.__pkey__', false],
      ['primaryEmailAddress.__store__', false],
      ['primaryEmailAddress', false],
      ['primaryPhoneNumber.priorityType', false],
      ['primaryPhoneNumber.value', false],
      ['primaryPhoneNumber.__pkey__', false],
      ['primaryPhoneNumber.__store__', false],
      ['primaryPhoneNumber', false],
      ['__pkey__', true],
    ],
  ],
  [
    'LocationMember',
    [
      ['person.fullName', false],
      ['person.pupil.__pkey__', false],
      ['person.pupil.__store__', false],
      ['person.pupil', false],
      ['person.firstName', false],
      ['person.lastNamePrefix', false],
      ['person.lastName', false],
      ['person.primaryEmailAddress.priorityType', false],
      ['person.primaryEmailAddress.value', false],
      ['person.primaryEmailAddress.__pkey__', false],
      ['person.primaryEmailAddress.__store__', false],
      ['person.primaryEmailAddress', false],
      ['person.primaryPhoneNumber.priorityType', false],
      ['person.primaryPhoneNumber.value', false],
      ['person.primaryPhoneNumber.__pkey__', false],
      ['person.primaryPhoneNumber.__store__', false],
      ['person.primaryPhoneNumber', false],
      ['person.__pkey__', false],
      ['person.__store__', false],
      ['person', false],
      ['location.name', false],
      ['location.__pkey__', false],
      ['location.__store__', false],
      ['location', false],
      ['type', false],
      ['validityRange.start', false],
      ['validityRange.end', false],
      ['validityRange', false],
      ['__pkey__', true],
    ],
  ],
];

export const persistenceSettings: PersistenceSettings = {
  version: 1,
  options: [
    //@ts-ignore
    ['LocationMember', { storeName: 'LocationMember', primaryKey: '@id', storeContent: true }],
    ['Person', { storeName: 'Person', primaryKey: '@id' }],
    ['Pupil', { storeName: 'Pupil', primaryKey: '@id' }],
    ['PupilEnrollment', { storeName: 'PupilEnrollment', primaryKey: '@id' }],
    ['SchoolClass', { storeName: 'SchoolClass', primaryKey: '@id' }],
    ['Location', { storeName: 'Location', primaryKey: '@id' }],
    ['PupilLevelYearStatus', { storeName: 'PupilLevelYearStatus', primaryKey: '@id' }],
    ['LevelYear', { storeName: 'LevelYear', primaryKey: '@id' }],
    ['EmailAddress', { storeName: 'EmailAddress', primaryKey: '@id' }],
    ['PhoneNumber', { storeName: 'PhoneNumber', primaryKey: '@id' }],
  ],
  links: [
    ['LocationMember', [['person', 'Person'], ['location', 'Location']]],
    ['Person', [['pupil', 'Pupil'], ['primaryEmailAddress', 'EmailAddress'], ['primaryPhoneNumber', 'PhoneNumber']]],
    ['Pupil', [['pupilEnrollments', 'PupilEnrollment'], ['pupilLevelYearStatuses', 'PupilLevelYearStatus']]],
    ['PupilEnrollment', [['schoolClass', 'SchoolClass']]],
    ['SchoolClass', [['location', 'Location']]],
    ['PupilLevelYearStatus', [['levelYear', 'LevelYear']]],
  ],
  mutations: { update: [], remove: [], indices: [] },
  triggers: [],
};

export const persistenceSettingsWithMutations: PersistenceSettings = {
  ...persistenceSettings,
  mutations: { update: ['LocationMember'], remove: [], indices: [] },
};
